Fix build failure due to missing std namespace
The fix resolves the following build failures:

src/CodeLocation.cc:52:1: error: ‘string’ does not name a type; did you
mean ‘stdin’?
 string

Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>